### ISSUE TITLE
mixes intltool and gettext, fails to build/autoreconf

### ISSUE THREAD

**Issue by ametzler** [gphoto/gtkam#5]
Hello,

gtkam git head fails at ./autogen.sh:

```
configure.ac:7: installing 'auto-aux/missing'
Makefile.am:22: warning: '%'-style pattern rules are a GNU make extension
configure.ac:239: error: required file 'intltool-extract.in' not found
configure.ac:239: error: required file 'intltool-merge.in' not found
configure.ac:239: error: required file 'intltool-update.in' not found
src/Makefile.am: installing 'auto-aux/depcomp'
autoreconf: automake failed with exit status: 1
[...]
+ rm -f m4/intltool.m4
+ test -n ln -s
+ ln -s /usr/share/aclocal/intltool.m4 m4/intltool.m4
+ :
+ grep INTLTOOL_MAKEFILE po/Makefile.in.in
+ exit 0
```

With the released tarball ./configure fails after "autoreconf -f -i " with

```
config.status: error: po/Makefile.in.in was not created by intltoolize.
```

Googling for this error message finds e.g. https://bugzilla.gnome.org/show_bug.cgi?id=705365#c7

>  David King 2013-08-06 08:19:01 UTC
> 
> Using both IT_PROG_INTLTOOL and AM_GNU_GETTEXT is a bug, so please file bugs against
> packages which do that. The intltool documentation now says that only IT_PROG_INTLTOOL
> should be used:
> https://code.launchpad.net/~robert-ancell/intltool/remove-am-gnu-gettext/+merge/114274

cu Andreas

**Comment by ametzler** [comment]
[0001-Stop-using-intltool.patch.txt](https://github.com/gphoto/gtkam/files/310381/0001-Stop-using-intltool.patch.txt)

Hello,
attached patch works for me. The respective changes to the build system were copied from the sample project linked in https://blog.du-a.org/2014/03/17/gettext-desktop/

cu Andreas

**Comment by msmeissn** [comment]
Thanks for the patch, I merged it in and it seems to work :)

**Comment by ndim** [comment]
We still have an `autogen.sh` file left which basically runs

    intltoolize --force --automake --debug
    rm -f po/Makefile.in.in
    autoreconf -vis

As far as I can, this fix means that the `intltoolize` and `rm` lines could be removed from `autogen.sh`, and you just forgot do do that?

If so, I will remove `autogen.sh` altogether and instruct people to just run `autoreconf` instead.

**Comment by msmeissn** [comment]
its all black magic, feel free to remove it, especially the desktop file internationalization.
